name: Gitleaks Scan

on:
  push:
  pull_request:

jobs:
  gitleaks:
    name: Scan for secrets with Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ""
